# Generated by Django 5.2.8 on 2026-02-22 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('google', 'Google')], max_length=25, verbose_name='Provedor')),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-5', 'GPT-5'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('o3', 'O3'), ('o4-mini', 'O4 Mini'), ('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('DeepSeek-R1', 'DeepSeek R1'), ('DeepSeek-V3', 'DeepSeek V3'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro')], max_length=50, verbose_name='Modelo')),
                ('tag', models.CharField(choices=[('recommended', 'Recomendado'), ('regular', 'Regular')], default='regular', max_length=15, verbose_name='Tag')),
                ('temperature', models.FloatField(default=0.5, verbose_name='Temperatura')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('input_price_per_1m_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Preço input/1M tokens')),
                ('output_price_per_1m_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Preço output/1M tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo LLM',
                'verbose_name_plural': 'Modelos LLM',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='UUID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('screen_context', models.CharField(blank=True, default='default', max_length=50, verbose_name='Contexto de tela')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ai_assistant.llmmodel', verbose_name='Modelo LLM')),
            ],
            options={
                'verbose_name': 'Sessão do Assistente',
                'verbose_name_plural': 'Sessões do Assistente',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Texto transcrito')),
                ('audio_file', models.FileField(upload_to='audio/transcriptions/%Y/%m/%d/', verbose_name='Arquivo de áudio')),
                ('audio_content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo do áudio')),
                ('audio_duration_seconds', models.FloatField(default=0, verbose_name='Duração (s)')),
                ('model_name', models.CharField(default='gpt-4o-transcribe', max_length=50, verbose_name='Modelo de transcrição')),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='ai_assistant.assistantsession', verbose_name='Sessão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_transcriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transcrição de Áudio',
                'verbose_name_plural': 'Transcrições de Áudio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('sender', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=20, verbose_name='Remetente')),
                ('screen_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Tela de origem')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Tokens de entrada')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Tokens de saída')),
                ('reasoning', models.TextField(blank=True, default='', verbose_name='Raciocínio')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.assistantsession', verbose_name='Sessão')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ai_assistant.llmmodel', verbose_name='Modelo utilizado')),
            ],
            options={
                'verbose_name': 'Mensagem do Assistente',
                'verbose_name_plural': 'Mensagens do Assistente',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['user', '-updated_at'], name='ai_assistan_user_id_4f92ac_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['uuid_code'], name='ai_assistan_uuid_co_253f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_assistan_session_a87398_idx'),
        ),
    ]
