# Generated by Django 5.2.8 on 2026-02-22 21:05

import ai_assistant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotranscription',
            name='audio_size',
            field=models.PositiveIntegerField(default=0, help_text='Size of the audio file in bytes', verbose_name='Tamanho do áudio (bytes)'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='audio_content_type',
            field=models.CharField(blank=True, default='', help_text='MIME type of the uploaded audio (e.g. audio/mpeg, audio/webm)', max_length=100, verbose_name='Tipo do áudio'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='audio_duration_seconds',
            field=models.FloatField(default=0, help_text='Duration of the audio in seconds (when available)', verbose_name='Duração (s)'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='audio_file',
            field=models.FileField(help_text='The original audio file that was transcribed', upload_to=ai_assistant.models.audio_upload_to, verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='content',
            field=models.TextField(blank=True, default='', help_text='The transcribed text returned by the model', verbose_name='Texto transcrito'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='input_tokens',
            field=models.IntegerField(default=0, help_text='Number of input (audio) tokens consumed', verbose_name='Tokens de entrada'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='model_name',
            field=models.CharField(default='gpt-4o-transcribe', help_text='Name of the audio model used for transcription', max_length=50, verbose_name='Modelo de transcrição'),
        ),
        migrations.AlterField(
            model_name='audiotranscription',
            name='output_tokens',
            field=models.IntegerField(default=0, help_text='Number of output (text) tokens produced', verbose_name='Tokens de saída'),
        ),
        migrations.AddIndex(
            model_name='audiotranscription',
            index=models.Index(fields=['user', '-created_at'], name='ai_audio_user_created_idx'),
        ),
    ]
