# Generated by Django 5.2.11 on 2026-04-25 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0002_audio_transcription_upgrade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(max_length=100, verbose_name="Tipo da acao"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Rotulo"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("tool", "Tool"), ("ui", "UI")],
                        default="tool",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposta"),
                            ("executed", "Executada"),
                            ("failed", "Falhou"),
                            ("rejected", "Rejeitada"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "screen_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Tela"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Entidade"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="ID da entidade",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resultado"
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="Erro"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="ai_assistant.assistantsession",
                        verbose_name="Sessao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acao do Assistente",
                "verbose_name_plural": "Acoes do Assistente",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_assistan_user_id_13206b_idx",
                    ),
                    models.Index(
                        fields=["session", "-created_at"],
                        name="ai_assistan_session_46348b_idx",
                    ),
                    models.Index(
                        fields=["action_type", "status"],
                        name="ai_assistan_action__a3cbcd_idx",
                    ),
                ],
            },
        ),
    ]
