# Generated by Django 5.2.8 on 2026-02-20 01:05

import django.db.models.deletion
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exerciseprogresslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprescription',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True, verbose_name='Descrição / instrução')),
                ('muscle_group', models.CharField(choices=[('chest', 'Peito'), ('back', 'Costas'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('forearms', 'Antebraço'), ('abs', 'Abdômen'), ('quadriceps', 'Quadríceps'), ('hamstrings', 'Posteriores'), ('glutes', 'Glúteos'), ('calves', 'Panturrilha'), ('full_body', 'Corpo inteiro'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Grupo muscular')),
                ('secondary_muscle', models.CharField(blank=True, choices=[('chest', 'Peito'), ('back', 'Costas'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('forearms', 'Antebraço'), ('abs', 'Abdômen'), ('quadriceps', 'Quadríceps'), ('hamstrings', 'Posteriores'), ('glutes', 'Glúteos'), ('calves', 'Panturrilha'), ('full_body', 'Corpo inteiro'), ('other', 'Outro')], default='', max_length=20, verbose_name='Músculo secundário')),
                ('equipment', models.CharField(choices=[('barbell', 'Barra'), ('dumbbell', 'Haltere'), ('machine', 'Máquina'), ('cable', 'Cabo/Polia'), ('bodyweight', 'Peso corporal'), ('kettlebell', 'Kettlebell'), ('band', 'Elástico'), ('smith', 'Smith Machine'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Equipamento')),
                ('image', models.ImageField(blank=True, null=True, upload_to=workouts.models.exercise_image_path, verbose_name='Foto do exercício')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de vídeo demonstrativo')),
                ('default_sets', models.PositiveSmallIntegerField(default=3, verbose_name='Séries padrão')),
                ('default_reps', models.CharField(default='8-12', max_length=30, verbose_name='Reps padrão')),
                ('default_rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Descanso padrão (s)')),
                ('tips', models.TextField(blank=True, verbose_name='Dicas de execução')),
                ('is_global', models.BooleanField(default=False, help_text='Exercícios globais ficam visíveis para todos os treinadores.', verbose_name='Disponível para todos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exerciseprescription',
            name='exercise_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='workouts.exercise', verbose_name='Exercício do catálogo'),
        ),
    ]
