# Generated by Django 5.2.8 on 2026-02-22 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('workouts', '0003_alter_exerciseprescription_name_exercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.CreateModel(
            name='ExerciseAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('exercise_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_alternative', to='workouts.exercise', verbose_name='Exercício substituto')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='workouts.exerciseprescription')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do plano')),
                ('objective', models.CharField(blank=True, max_length=300, verbose_name='Objetivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='athletes.athlete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.trainingplan'),
        ),
    ]
