# Generated by Django 5.2.11 on 2026-04-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_student_owned_training(apps, schema_editor):
    TrainingPlan = apps.get_model("workouts", "TrainingPlan")
    WorkoutPlan = apps.get_model("workouts", "WorkoutPlan")

    for plan in TrainingPlan.objects.select_related("athlete").only("pk", "created_by_id", "athlete__user_id"):
        if plan.created_by_id == plan.athlete.user_id:
            TrainingPlan.objects.filter(pk=plan.pk).update(origin="self_created")

    for workout in WorkoutPlan.objects.select_related("athlete").only("pk", "created_by_id", "athlete__user_id"):
        if workout.created_by_id == workout.athlete.user_id:
            WorkoutPlan.objects.filter(pk=workout.pk).update(origin="self_created")


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0005_workoutsession_workoutsetlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="origin",
            field=models.CharField(
                choices=[
                    ("self_created", "Criado pelo aluno"),
                    ("ai_suggested", "Sugerido pela IA"),
                    ("trainer_prescribed", "Prescrito pelo professor"),
                    ("template", "Template"),
                    ("imported", "Importado"),
                ],
                default="trainer_prescribed",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="origin",
            field=models.CharField(
                choices=[
                    ("self_created", "Criado pelo aluno"),
                    ("ai_suggested", "Sugerido pela IA"),
                    ("trainer_prescribed", "Prescrito pelo professor"),
                    ("template", "Template"),
                    ("imported", "Importado"),
                ],
                default="trainer_prescribed",
                max_length=30,
            ),
        ),
        migrations.RunPython(mark_existing_student_owned_training, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="workoutsession",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_workout_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
