# Generated by Django 5.2.8 on 2026-02-22 22:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Contato de emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone emergência')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Profissão')),
                ('training_experience', models.CharField(blank=True, choices=[('none', 'Nenhuma (sedentário)'), ('beginner', 'Iniciante (< 6 meses)'), ('intermediate', 'Intermediário (6 meses – 2 anos)'), ('advanced', 'Avançado (2 – 5 anos)'), ('elite', 'Elite (> 5 anos)')], max_length=20, verbose_name='Nível de experiência')),
                ('training_frequency', models.PositiveSmallIntegerField(blank=True, help_text='Quantas vezes por semana o aluno treina ou pretende treinar', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='Frequência semanal de treino')),
                ('primary_goal', models.CharField(blank=True, choices=[('hypertrophy', 'Hipertrofia'), ('strength', 'Força'), ('weight_loss', 'Emagrecimento'), ('health', 'Saúde e qualidade de vida'), ('sport', 'Performance esportiva'), ('rehab', 'Reabilitação'), ('flexibility', 'Flexibilidade / Mobilidade'), ('endurance', 'Resistência / Condicionamento'), ('other', 'Outro')], max_length=20, verbose_name='Objetivo principal')),
                ('secondary_goal', models.CharField(blank=True, max_length=200, verbose_name='Objetivo secundário')),
                ('medical_conditions', models.TextField(blank=True, help_text='Ex.: hipertensão, diabetes, asma, cardiopatia…', verbose_name='Condições médicas / Doenças')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('injuries_history', models.TextField(blank=True, help_text='Descreva lesões passadas ou atuais', verbose_name='Histórico de lesões')),
                ('surgeries', models.TextField(blank=True, verbose_name='Cirurgias realizadas')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('pain_complaints', models.TextField(blank=True, help_text='Dor articular, muscular, postural etc.', verbose_name='Queixas de dor / Desconfortos')),
                ('physical_limitations', models.TextField(blank=True, help_text='Movimentos que não consegue realizar, restrições médicas…', verbose_name='Limitações físicas')),
                ('smoker', models.BooleanField(default=False, verbose_name='Fumante')),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'Não consome'), ('social', 'Social (eventual)'), ('moderate', 'Moderado (1-2x/semana)'), ('frequent', 'Frequente (3+x/semana)')], default='none', max_length=10, verbose_name='Consumo de álcool')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Horas de sono por noite')),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('moderate', 'Moderado'), ('high', 'Alto'), ('very_high', 'Muito alto')], max_length=10, verbose_name='Nível de estresse')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Intolerância, dieta vegetariana, etc.', verbose_name='Restrições alimentares')),
                ('supplements', models.TextField(blank=True, verbose_name='Suplementos em uso')),
                ('additional_notes', models.TextField(blank=True, help_text='Escreva aqui qualquer informação adicional. A IA irá organizar e formatar.', verbose_name='Anamnese geral (texto livre)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis_records', to='athletes.athlete')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_at', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10')), django.core.validators.MaxValueValidator(Decimal('400'))], verbose_name='Peso (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50')), django.core.validators.MaxValueValidator(Decimal('300'))], verbose_name='Altura (cm)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('70'))], verbose_name='Gordura corporal (%)')),
                ('neck_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Pescoço (cm)')),
                ('shoulders_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ombros (cm)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tórax / Peito (cm)')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('abdomen_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Abdômen (cm)')),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Quadril (cm)')),
                ('right_arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Braço direito (cm)')),
                ('left_arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Braço esquerdo (cm)')),
                ('right_forearm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Antebraço direito (cm)')),
                ('left_forearm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Antebraço esquerdo (cm)')),
                ('right_thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Coxa direita (cm)')),
                ('left_thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Coxa esquerda (cm)')),
                ('right_calf_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Panturrilha direita (cm)')),
                ('left_calf_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Panturrilha esquerda (cm)')),
                ('triceps_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra tricipital (mm)')),
                ('subscapular_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra subescapular (mm)')),
                ('suprailiac_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra suprailíaca (mm)')),
                ('abdominal_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra abdominal (mm)')),
                ('thigh_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra da coxa (mm)')),
                ('chest_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra peitoral (mm)')),
                ('midaxillary_skinfold_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Dobra axilar média (mm)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações da avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assessments', to='athletes.athlete')),
            ],
            options={
                'verbose_name': 'Avaliação Física',
                'verbose_name_plural': 'Avaliações Físicas',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
