# Generated by Django 5.2.11 on 2026-04-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def mark_existing_relationships_active(apps, schema_editor):
    Athlete = apps.get_model("athletes", "Athlete")
    Athlete.objects.filter(trainer__isnull=False).update(
        relationship_status="active",
        relationship_started_at=F("created_at"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0003_athlete_allow_student_load_updates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="relationship_ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="athlete",
            name="relationship_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="athlete",
            name="relationship_status",
            field=models.CharField(
                choices=[
                    ("independent", "Independente"),
                    ("invited", "Convite pendente"),
                    ("active", "Acompanhado"),
                    ("paused", "Pausado"),
                    ("ended", "Encerrado"),
                ],
                default="independent",
                max_length=20,
            ),
        ),
        migrations.RunPython(mark_existing_relationships_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="athlete",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athletes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
